### ISSUE TITLE
Just a question. Is there any plans to migrate from Java EE to Jakarta EE?

### ISSUE THREAD

**Issue by urigon** [authlete/authlete-java-jaxrs#38]
I am using this library from spring-boot 2.7.x. And I want to upgrade to spring-boot 3 which uses Jakarta EE.

**Comment by hefa** [comment]
Hi, we are working on a jakarta version of this library. It should be available within 2 weeks.

**Comment by urigon** [comment]
thank you for your quick response!

**Comment by hefa** [comment]
This version of the library is using Jakarta https://mvnrepository.com/artifact/com.authlete/authlete-java-jakarta/2.68
Please let us know if there are any issues with using it.

**Comment by urigon** [comment]
Hi, @hefa 

I changed to the jakarta version and worked fine.

I also made a [pull request](https://github.com/authlete/spring-oauth-server/pull/3) to the repository which I referred in the beginning of using Authlete Api.

**Comment by hefa** [comment]
@urigon Great, thank you for the update. We will check the PR.
